# Generated by Backlink Pilot. Human-only assisted login helper.
# This script does not submit products, run scout, run run-plan, pay, or bypass challenges.
param(
  [switch]$DryRun
)
$ErrorActionPreference = "Stop"

function Invoke-ManualLogin {
  param(
    [string]$Order,
    [string]$TargetId,
    [string]$Name,
    [string]$Domain,
    [string]$Profile,
    [string]$LoginUrl
  )
  Write-Host ""
  Write-Host "[$Order] $TargetId $Domain" -ForegroundColor Cyan
  Write-Host "Profile: $Profile"
  Write-Host "Login URL: $LoginUrl"
  Write-Host "Safety: human login only; no payment; no CAPTCHA/Cloudflare bypass; no submission." -ForegroundColor Yellow
  $answer = Read-Host "Type LOGIN to open manual login browser, SKIP to skip"
  if ($answer -ne "LOGIN") {
    Write-Host "Skipped $TargetId"
    return
  }
  if ($DryRun) {
    Write-Host "DRY RUN: node src/cli.js auth login --profile $Profile --url $LoginUrl"
    Write-Host "DRY RUN: node src/cli.js auth status --profile $Profile"
    return
  }
  & node src/cli.js auth login --profile $Profile --url $LoginUrl
  if ($LASTEXITCODE -ne 0) { throw "auth login failed for $TargetId" }
  & node src/cli.js auth status --profile $Profile
  if ($LASTEXITCODE -ne 0) { throw "auth status failed for $TargetId" }
}

Write-Host "Backlink Pilot assisted login operator pack" -ForegroundColor Green
Write-Host "No real submission will be performed by this script." -ForegroundColor Yellow
Invoke-ManualLogin -Order '1' -TargetId 'beta-list' -Name 'Beta List' -Domain 'betalist.com' -Profile 'beta-list' -LoginUrl 'https://betalist.com/sign_in'
Invoke-ManualLogin -Order '2' -TargetId 'chatgptdemo' -Name 'ChatGPT demo' -Domain 'chatgptdemo.com' -Profile 'chatgptdemo' -LoginUrl 'https://chatgptdemo.com/submit-new-ai-tool'
Invoke-ManualLogin -Order '3' -TargetId 'promptzone' -Name 'Promptzone' -Domain 'promptzone.com' -Profile 'promptzone' -LoginUrl 'https://www.promptzone.com/new'
Invoke-ManualLogin -Order '4' -TargetId 'resource-fyi' -Name 'Resource fyi' -Domain 'resource.fyi' -Profile 'resource-fyi' -LoginUrl 'https://resource.fyi/login'
Invoke-ManualLogin -Order '5' -TargetId 'sitelike' -Name 'Sitelike' -Domain 'sitelike.org' -Profile 'sitelike' -LoginUrl 'https://www.sitelike.org/add-site'
Invoke-ManualLogin -Order '6' -TargetId '247webdirectory' -Name '247WebDirectory' -Domain '247webdirectory.com' -Profile '247webdirectory' -LoginUrl 'https://www.247webdirectory.com/'
Invoke-ManualLogin -Order '7' -TargetId 'asr' -Name 'ASR' -Domain 'activesearchresults.com' -Profile 'asr' -LoginUrl 'https://www.activesearchresults.com/addwebsite.php'
Invoke-ManualLogin -Order '8' -TargetId 'ai-ailookme' -Name 'AI工具箱 (ailookme)' -Domain 'ailookme.com' -Profile 'ai-ailookme' -LoginUrl 'https://www.ailookme.com/%e7%bd%91%e5%9d%80%e6%8f%90%e4%ba%a4'
Invoke-ManualLogin -Order '9' -TargetId 'top-best-alternatives' -Name 'Top Best Alternatives' -Domain 'topbestalternatives.com' -Profile 'top-best-alternatives' -LoginUrl 'https://www.topbestalternatives.com/'
Invoke-ManualLogin -Order '10' -TargetId 'xinquji-com' -Name '新趣集' -Domain 'xinquji.com' -Profile 'xinquji-com' -LoginUrl 'https://xinquji.com/submit'

Write-Host ""
Write-Host "After completing logins, run this read-only refresh command:" -ForegroundColor Green
Write-Host 'node src/cli.js targets auth-workflow-refresh backlink-url/assisted-submission-pack/auth-login-rescout-queue.csv backlink-url/assisted-submission-pack/auth-login-plan-batch-001.json backlink-url/assisted-submission-pack/auth-login-plan-batch-002.json backlink-url/assisted-submission-pack/auth-login-plan-batch-003.json --registry resources/targets.canonical.yaml --product-config backlink-url/submission-materials/xtimer.config.yaml --output-dir backlink-url/assisted-submission-pack --next-name auth-login-next-current --summary-name auth-workflow-refresh-summary --next-limit 10'
