# Generated by Backlink Pilot. Human-only assisted login helper.
# This script does not submit products, run scout, run run-plan, pay, or bypass challenges.
param(
  [switch]$DryRun
)
$ErrorActionPreference = "Stop"

function Invoke-ManualLogin {
  param(
    [string]$Order,
    [string]$TargetId,
    [string]$Name,
    [string]$Domain,
    [string]$Profile,
    [string]$LoginUrl
  )
  Write-Host ""
  Write-Host "[$Order] $TargetId $Domain" -ForegroundColor Cyan
  Write-Host "Profile: $Profile"
  Write-Host "Login URL: $LoginUrl"
  Write-Host "Safety: human login only; no payment; no CAPTCHA/Cloudflare bypass; no submission." -ForegroundColor Yellow
  $answer = Read-Host "Type LOGIN to open manual login browser, SKIP to skip"
  if ($answer -ne "LOGIN") {
    Write-Host "Skipped $TargetId"
    return
  }
  if ($DryRun) {
    Write-Host "DRY RUN: node src/cli.js auth login --profile $Profile --url $LoginUrl"
    Write-Host "DRY RUN: node src/cli.js auth status --profile $Profile"
    return
  }
  & node src/cli.js auth login --profile $Profile --url $LoginUrl
  if ($LASTEXITCODE -ne 0) { throw "auth login failed for $TargetId" }
  & node src/cli.js auth status --profile $Profile
  if ($LASTEXITCODE -ne 0) { throw "auth status failed for $TargetId" }
}

Write-Host "Backlink Pilot assisted login operator pack" -ForegroundColor Green
Write-Host "No real submission will be performed by this script." -ForegroundColor Yellow
Invoke-ManualLogin -Order '1' -TargetId 'beta-list' -Name 'Beta List' -Domain 'betalist.com' -Profile 'beta-list' -LoginUrl 'https://betalist.com/sign_in'
Invoke-ManualLogin -Order '2' -TargetId 'chatgptdemo' -Name 'ChatGPT demo' -Domain 'chatgptdemo.com' -Profile 'chatgptdemo' -LoginUrl 'https://chatgptdemo.com/submit-new-ai-tool'
Invoke-ManualLogin -Order '3' -TargetId 'promptzone' -Name 'Promptzone' -Domain 'promptzone.com' -Profile 'promptzone' -LoginUrl 'https://www.promptzone.com/new'
Invoke-ManualLogin -Order '4' -TargetId 'resource-fyi' -Name 'Resource fyi' -Domain 'resource.fyi' -Profile 'resource-fyi' -LoginUrl 'https://resource.fyi/login'
Invoke-ManualLogin -Order '5' -TargetId 'sitelike' -Name 'Sitelike' -Domain 'sitelike.org' -Profile 'sitelike' -LoginUrl 'https://www.sitelike.org/add-site'
Invoke-ManualLogin -Order '6' -TargetId 'ai-tool-guru' -Name 'AI Tool guru' -Domain 'aitoolguru.com' -Profile 'ai-tool-guru' -LoginUrl 'https://aitoolguru.com/login'
Invoke-ManualLogin -Order '7' -TargetId 'ai-tools-arena' -Name 'AI Tools Arena' -Domain 'aitoolsarena.com' -Profile 'ai-tools-arena' -LoginUrl 'https://aitoolsarena.com/ai-tools-list-new'
Invoke-ManualLogin -Order '8' -TargetId 'alternative-me' -Name 'Alternative' -Domain 'alternative.me' -Profile 'alternative-me' -LoginUrl 'https://alternative.me/how-to/suggest-alternatives'
Invoke-ManualLogin -Order '9' -TargetId 'bestofai' -Name 'BestOfAI' -Domain 'bestofai.com' -Profile 'bestofai' -LoginUrl 'https://bestofai.com/tool/add'
Invoke-ManualLogin -Order '10' -TargetId 'f6s' -Name 'F6S' -Domain 'f6s.com' -Profile 'f6s' -LoginUrl 'https://www.f6s.com/'

Write-Host ""
Write-Host "After completing logins, run this read-only refresh command:" -ForegroundColor Green
Write-Host '"node" "src/cli.js" "targets" "auth-workflow-refresh" "backlink-url/assisted-submission-pack/resolved-auth-login/auth-login-resolved-direct-login-queue.csv" "backlink-url/assisted-submission-pack/resolved-direct-login/auth-login-plan-batch-resolved-001.json" "backlink-url/assisted-submission-pack/resolved-direct-login/auth-login-plan-batch-resolved-002.json" "--registry" "resources/targets.canonical.yaml" "--auth-dir" "playwright/.auth" "--output-dir" "backlink-url/assisted-submission-pack/resolved-direct-login" "--next-name" "auth-login-next-resolved-current" "--summary-name" "auth-workflow-refresh-resolved-summary" "--next-limit" "10" "--rescout-limit" "100"'
